# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 499)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("icons/db.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridTabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.gridTabWidget.setObjectName("gridTabWidget")
        self.gridTabWidgetPage1 = QtWidgets.QWidget()
        self.gridTabWidgetPage1.setObjectName("gridTabWidgetPage1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridTabWidgetPage1)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.gridTabWidgetPage1)
        self.commandLinkButton_2.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("icons/lc_dbtableedit.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.commandLinkButton_2.setIcon(icon1)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.gridLayout_3.addWidget(self.commandLinkButton_2, 0, 1, 1, 1)
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.gridTabWidgetPage1)
        self.commandLinkButton_3.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap("icons/lc_dbtabledelete.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.commandLinkButton_3.setIcon(icon2)
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.gridLayout_3.addWidget(self.commandLinkButton_3, 0, 2, 1, 1)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.gridTabWidgetPage1)
        self.commandLinkButton.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap("icons/lc_dbnewtable.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.commandLinkButton.setIcon(icon3)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.gridLayout_3.addWidget(self.commandLinkButton, 0, 0, 1, 1)
        self.treeView = QtWidgets.QTreeView(self.gridTabWidgetPage1)
        self.treeView.setObjectName("treeView")
        self.gridLayout_3.addWidget(self.treeView, 2, 0, 1, 4)
        self.gridTabWidget.addTab(self.gridTabWidgetPage1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.newRecordButton = QtWidgets.QPushButton(self.tab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap("icons/sc_newrecord.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.newRecordButton.setIcon(icon4)
        self.newRecordButton.setObjectName("newRecordButton")
        self.gridLayout_4.addWidget(self.newRecordButton, 0, 3, 1, 1)
        self.deleteRecordButton = QtWidgets.QPushButton(self.tab)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap("icons/sc_deleterecord.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.deleteRecordButton.setIcon(icon5)
        self.deleteRecordButton.setObjectName("deleteRecordButton")
        self.gridLayout_4.addWidget(self.deleteRecordButton, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.reloadTableButton = QtWidgets.QPushButton(self.tab)
        self.reloadTableButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap("icons/sc_refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.reloadTableButton.setIcon(icon6)
        self.reloadTableButton.setObjectName("reloadTableButton")
        self.gridLayout_4.addWidget(self.reloadTableButton, 0, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setObjectName("tableView")
        self.gridLayout_4.addWidget(self.tableView, 1, 0, 1, 5)
        self.gridTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.queryExecButton = QtWidgets.QPushButton(self.tab_2)
        self.queryExecButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap("icons/lc_sbaexecutesql.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.queryExecButton.setIcon(icon7)
        self.queryExecButton.setObjectName("queryExecButton")
        self.gridLayout_5.addWidget(self.queryExecButton, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        self.queryTextEdit = QtWidgets.QTextEdit(self.tab_2)
        self.queryTextEdit.setObjectName("queryTextEdit")
        self.gridLayout_5.addWidget(self.queryTextEdit, 1, 0, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 3)
        self.queryResultText = QtWidgets.QTextEdit(self.tab_2)
        self.queryResultText.setReadOnly(True)
        self.queryResultText.setObjectName("queryResultText")
        self.gridLayout_6.addWidget(self.queryResultText, 3, 0, 1, 1)
        self.queryTableView = QtWidgets.QTableView(self.tab_2)
        self.queryTableView.setObjectName("queryTableView")
        self.gridLayout_6.addWidget(self.queryTableView, 2, 0, 1, 3)
        self.saveQueryAsView = QtWidgets.QPushButton(self.tab_2)
        self.saveQueryAsView.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(
            QtGui.QPixmap("icons/lc_dbnewviewsql.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.saveQueryAsView.setIcon(icon8)
        self.saveQueryAsView.setObjectName("saveQueryAsView")
        self.gridLayout_6.addWidget(self.saveQueryAsView, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_6.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridTabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.gridTabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 691, 19))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen_Recent = QtWidgets.QMenu(self.menuFile)
        self.menuOpen_Recent.setObjectName("menuOpen_Recent")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(
            QtGui.QPixmap("icons/lc_newdoc.png"), QtGui.QIcon.Normal, QtGui.QIcon.On
        )
        self.actionNew.setIcon(icon9)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(
            QtGui.QPixmap("icons/lc_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionOpen.setIcon(icon10)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(
            QtGui.QPixmap("icons/lc_quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionExit.setIcon(icon11)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate_Tables = QtWidgets.QAction(MainWindow)
        self.actionCreate_Tables.setObjectName("actionCreate_Tables")
        self.actionEdit_Table = QtWidgets.QAction(MainWindow)
        self.actionEdit_Table.setObjectName("actionEdit_Table")
        self.actionModify_Table = QtWidgets.QAction(MainWindow)
        self.actionModify_Table.setObjectName("actionModify_Table")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(
            QtGui.QPixmap("icons/sc_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On
        )
        self.actionSave.setIcon(icon12)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setEnabled(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(
            QtGui.QPixmap("icons/lc_closedoc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.actionClose.setIcon(icon13)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuOpen_Recent.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCreate_Tables)
        self.menuEdit.addAction(self.actionEdit_Table)
        self.menuEdit.addAction(self.actionModify_Table)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionOpen)
        self.mainToolBar.addAction(self.actionNew)
        self.mainToolBar.addAction(self.actionClose)

        self.retranslateUi(MainWindow)
        self.gridTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyQt SqLite"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "Modify Table"))
        self.commandLinkButton_3.setText(_translate("MainWindow", "Delete Table"))
        self.commandLinkButton.setText(_translate("MainWindow", "Create Table"))
        self.gridTabWidget.setTabText(
            self.gridTabWidget.indexOf(self.gridTabWidgetPage1),
            _translate("MainWindow", "Tables"),
        )
        self.label.setText(_translate("MainWindow", "Table:"))
        self.newRecordButton.setText(_translate("MainWindow", "New Record"))
        self.deleteRecordButton.setText(_translate("MainWindow", "Delete Record"))
        self.gridTabWidget.setTabText(
            self.gridTabWidget.indexOf(self.tab), _translate("MainWindow", "Browse")
        )
        self.gridTabWidget.setTabText(
            self.gridTabWidget.indexOf(self.tab_2),
            _translate("MainWindow", "Execute SQL"),
        )
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuOpen_Recent.setTitle(_translate("MainWindow", "Open &Recent"))
        self.menuEdit.setTitle(_translate("MainWindow", "&Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "&Quit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionCreate_Tables.setText(_translate("MainWindow", "&Create Table"))
        self.actionCreate_Tables.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionEdit_Table.setText(_translate("MainWindow", "E&dit Table"))
        self.actionEdit_Table.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionModify_Table.setText(_translate("MainWindow", "&Modify Table"))
        self.actionModify_Table.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionSave.setText(_translate("MainWindow", "Close"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
